"""Add Event model

Revision ID: 38d29bdd6f2f
Revises: fe79b2c21052
Create Date: 2025-03-27 10:04:53.060148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d29bdd6f2f'
down_revision: Union[str, None] = 'fe79b2c21052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sandbox_id', sa.UUID(), nullable=False),
    sa.Column('container_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'unknown', name='sandbox_status_enum', native_enum=False), server_default='pending', nullable=False),
    sa.ForeignKeyConstraint(['sandbox_id'], ['sandboxes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_container_id'), 'events', ['container_id'], unique=True)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=True)
    op.add_column('sandboxes', sa.Column('container_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_sandboxes_container_id'), 'sandboxes', ['container_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sandboxes_container_id'), table_name='sandboxes')
    op.drop_column('sandboxes', 'container_id')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_container_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
