"""Add sandbox model

Revision ID: fe79b2c21052
Revises: 127e36433207
Create Date: 2025-03-26 23:56:46.234442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe79b2c21052'
down_revision: Union[str, None] = '127e36433207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sandboxes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('twitter_account_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'unknown', name='sandbox_status_enum', native_enum=False), server_default='pending', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sandboxes_id'), 'sandboxes', ['id'], unique=True)
    op.create_index(op.f('ix_sandboxes_twitter_account_id'), 'sandboxes', ['twitter_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sandboxes_twitter_account_id'), table_name='sandboxes')
    op.drop_index(op.f('ix_sandboxes_id'), table_name='sandboxes')
    op.drop_table('sandboxes')
    # ### end Alembic commands ###
